"""Persistent single-kernel CG solver (cuTile code generation).

Uses ct.num_blocks(0) persistent loop with spinlock synchronization
between CG phases (SpMV, dot, axpy). Follows the layernorm.py backward
pass pattern for atomic synchronization.
"""

from __future__ import annotations

from cutile_stencil.codegen.emitter import CodeEmitter
from cutile_stencil.config import SolverConfig, DEFAULT_SOLVER


def generate_persistent_cg(solver_config: SolverConfig | None = None) -> str:
    """Generate a persistent CG kernel that runs the entire solve in one launch."""
    cfg = solver_config or DEFAULT_SOLVER
    e = CodeEmitter()
    e.line('"""Persistent single-kernel CG solver (auto-generated).')
    e.line("")
    e.line("All CG iterations run inside a single @ct.kernel using")
    e.line("ct.num_blocks(0) persistent loop with spinlock barriers.")
    e.line('"""')
    e.blank()
    e.line("import cuda.tile as ct")
    e.line("import torch")
    e.blank()
    e.line("ConstInt = ct.Constant[int]")
    e.blank()

    # Persistent kernel
    e.line("@ct.kernel")
    e.line("def persistent_cg_kernel(")
    e.line("    # Matrix data (DIA format)")
    e.line("    diag_vals, offsets_arr, num_diags_val,")
    e.line("    # Vectors: x, b, r, p, Ap")
    e.line("    x, b, r, p, Ap,")
    e.line("    # Scalars: r_dot_r, p_dot_Ap, convergence flag")
    e.line("    scalars, locks,")
    e.line("    # Config")
    e.line("    max_iter: ConstInt, TILE: ConstInt,")
    e.line("):")
    with e.indent():
        e.line("bid = ct.bid(0)")
        e.line("num_blocks = ct.num_blocks(0)")
        e.line("N = x.shape[0]")
        e.line("num_tiles = ct.cdiv(N, TILE)")
        e.blank()
        e.line("for iteration in range(max_iter):")
        with e.indent():
            e.line("# ── Phase 1: SpMV  Ap = A @ p ─────────────────")
            e.line("for tile_id in range(bid, num_tiles, num_blocks):")
            with e.indent():
                e.line("acc = ct.full((TILE,), 0.0, dtype=ct.float64)")
                e.line("for d in range(num_diags_val):")
                with e.indent():
                    e.line("dv = ct.load(diag_vals, index=(d, tile_id), shape=(1, TILE), padding_mode=ct.PaddingMode.ZERO)")
                    e.line("dv = ct.reshape(dv, (TILE,))")
                    e.line("base = tile_id * TILE + ct.arange(TILE, dtype=torch.int32)")
                    e.line("off = ct.load(offsets_arr, index=d, shape=())")
                    e.line("x_vals = ct.gather(p, base + off)")
                    e.line("acc = acc + dv * x_vals")
                e.line("ct.store(Ap, index=(tile_id,), tile=acc)")
            e.blank()
            e.line("# ── Barrier: wait for all blocks to finish SpMV ──")
            e.line("while ct.atomic_cas(locks, 0, 0, 1, memory_order=ct.MemoryOrder.ACQUIRE) == 1: pass")
            e.line("ct.atomic_xchg(locks, 0, 0, memory_order=ct.MemoryOrder.RELEASE)")
            e.blank()
            e.line("# ── Phase 2: dot products (p^T Ap, r^T r) ────────")
            e.line("for tile_id in range(bid, num_tiles, num_blocks):")
            with e.indent():
                e.line("tp = ct.load(p, index=(tile_id,), shape=(TILE,))")
                e.line("tap = ct.load(Ap, index=(tile_id,), shape=(TILE,))")
                e.line("ct.atomic_add(scalars, (0,), ct.sum(tp * tap))  # p^T Ap")
                e.line("tr = ct.load(r, index=(tile_id,), shape=(TILE,))")
                e.line("ct.atomic_add(scalars, (1,), ct.sum(tr * tr))   # r^T r")
            e.blank()
            e.line("# ── Barrier ──")
            e.line("while ct.atomic_cas(locks, 1, 0, 1, memory_order=ct.MemoryOrder.ACQUIRE) == 1: pass")
            e.line("ct.atomic_xchg(locks, 1, 0, memory_order=ct.MemoryOrder.RELEASE)")
            e.blank()
            e.line("# ── Phase 3: update x, r, p ──────────────────────")
            e.line("for tile_id in range(bid, num_tiles, num_blocks):")
            with e.indent():
                e.line("tx = ct.load(x, index=(tile_id,), shape=(TILE,))")
                e.line("tr = ct.load(r, index=(tile_id,), shape=(TILE,))")
                e.line("tp = ct.load(p, index=(tile_id,), shape=(TILE,))")
                e.line("tap = ct.load(Ap, index=(tile_id,), shape=(TILE,))")
                e.line("# Read computed scalars")
                e.line("r_dot_r = ct.load(scalars, index=1, shape=())")
                e.line("p_dot_Ap = ct.load(scalars, index=0, shape=())")
                e.line("alpha = r_dot_r / p_dot_Ap")
                e.line("# x += alpha * p")
                e.line("ct.store(x, index=(tile_id,), tile=tx + alpha * tp)")
                e.line("# r -= alpha * Ap")
                e.line("new_r = tr - alpha * tap")
                e.line("ct.store(r, index=(tile_id,), tile=new_r)")
                e.line("# Accumulate new r^T r")
                e.line("ct.atomic_add(scalars, (2,), ct.sum(new_r * new_r))")
            e.blank()
            e.line("# ── Barrier ──")
            e.line("while ct.atomic_cas(locks, 2, 0, 1, memory_order=ct.MemoryOrder.ACQUIRE) == 1: pass")
            e.line("ct.atomic_xchg(locks, 2, 0, memory_order=ct.MemoryOrder.RELEASE)")
            e.blank()
            e.line("# ── Phase 4: update p, reset scalars ─────────────")
            e.line("new_r_dot_r = ct.load(scalars, index=2, shape=())")
            e.line("old_r_dot_r = ct.load(scalars, index=1, shape=())")
            e.line("beta = new_r_dot_r / old_r_dot_r")
            e.line("for tile_id in range(bid, num_tiles, num_blocks):")
            with e.indent():
                e.line("tr = ct.load(r, index=(tile_id,), shape=(TILE,))")
                e.line("tp = ct.load(p, index=(tile_id,), shape=(TILE,))")
                e.line("ct.store(p, index=(tile_id,), tile=tr + beta * tp)")
    e.blank()
    e.blank()
    e.line("def launch_persistent_cg(diag_vals, offsets_arr, num_diags,")
    e.line("                         x, b, tol=1e-10, max_iter=1000,")
    e.line("                         tile_size=256, num_sms=108):")
    with e.indent():
        e.line('"""Launch the persistent CG kernel."""')
        e.line("N = x.shape[0]")
        e.line("r = b.clone()  # Initial: r = b (assuming x0 = 0)")
        e.line("p = r.clone()")
        e.line("Ap = torch.zeros_like(x)")
        e.line(f"scalars = torch.zeros({cfg.persistent_spinlock_size}, dtype=x.dtype, device=x.device)")
        e.line(f"locks = torch.zeros({cfg.persistent_spinlock_size}, dtype=torch.int32, device=x.device)")
        e.line("stream = torch.cuda.current_stream()")
        e.line("grid = (num_sms,)")
        e.line("ct.launch(stream, grid, persistent_cg_kernel, (")
        e.line("    diag_vals, offsets_arr, num_diags,")
        e.line("    x, b, r, p, Ap,")
        e.line("    scalars, locks,")
        e.line("    max_iter, tile_size,")
        e.line("))")
        e.line("return x")
    return e.render()
